web:
 image: nginx:latest
 ports:
  - "80:80"
 volumes:
  - ./Dockerfiles/web/default.conf:/etc/nginx/conf.d/default.conf
  - ./data:/data
 links:
  - php
  - db
php:
 image: php:7-fpm
 volumes:
  - ./data:/data
 links:
  - db
db:
 image: mariadb:10.3
 restart: always
 volumes:
 - container-volume:/var/lib/mysql
 environment:
   MYSQL_ROOT_PASSWORD: Task54556
   MYSQL_DATABASE: task
   MYSQL_USER: task
   MYSQL_PASSWORD: Task54556